"""Campaign analysis: from cells to a reportable finding."""

from __future__ import annotations

from xai_gov.analysis.anytime import (
    ConfidenceSequence,
    DirectionalEvidence,
    EvidenceVerdict,
    MeanShiftMartingale,
    combine_evidence,
    confidence_sequence,
    directional_evidence,
)
from xai_gov.analysis.calibration import (
    CALIBRATION_STATISTICS,
    DemandSummary,
    Posterior,
    PredictiveCheck,
    Prior,
    abc_rejection,
    bootstrap_scales,
    default_priors,
    posterior_predictive_check,
    prior_widths,
    sequential_abc,
    summary_distance,
)
from xai_gov.analysis.campaign import (
    CampaignCell,
    CampaignRunner,
    CellResult,
    apply_exclusions,
    plan_campaign,
)
from xai_gov.analysis.data import (
    DemandSeries,
    load_series,
    resolve_series,
    synthetic_series,
)
from xai_gov.analysis.figures import (
    ArmSeries,
    build_figures,
    evidence_bars,
    grouped_bars,
    network_diagram,
    paired_dots,
    series_from_aggregates,
    strategic_scatter,
    write_figures,
)
from xai_gov.analysis.frontier import (
    THEOREM_3_OBJECTIVES,
    Objective,
    ParetoFrontier,
    compute_frontier,
)
from xai_gov.analysis.hierarchical import (
    ArmPosterior,
    VarianceDecomposition,
    decompose,
    decompose_all,
)
from xai_gov.analysis.power import PowerAnalysis, analyse_power, required_replicates
from xai_gov.analysis.preregistration import (
    Hypothesis,
    Preregistration,
    build_preregistration,
    load_seal,
    verify_seal,
)
from xai_gov.analysis.sensitivity import (
    Parameter,
    ParameterSpace,
    SensitivityReport,
    SobolIndices,
    build_parameter_space,
    sobol_analysis,
)
from xai_gov.analysis.strategic import StrategicValue, strategic_value
from xai_gov.analysis.sweeps import (
    BREAK_EVEN_COSTS,
    SEVERITY_LEVELS,
    ParameterSweep,
    SweepPoint,
    SweepResult,
)

__all__ = [
    "BREAK_EVEN_COSTS",
    "CALIBRATION_STATISTICS",
    "SEVERITY_LEVELS",
    "THEOREM_3_OBJECTIVES",
    "ArmPosterior",
    "ArmSeries",
    "CampaignCell",
    "CampaignRunner",
    "CellResult",
    "ConfidenceSequence",
    "DemandSeries",
    "DemandSummary",
    "DirectionalEvidence",
    "EvidenceVerdict",
    "Hypothesis",
    "MeanShiftMartingale",
    "Objective",
    "Parameter",
    "ParameterSpace",
    "ParameterSweep",
    "ParetoFrontier",
    "Posterior",
    "PowerAnalysis",
    "PredictiveCheck",
    "Preregistration",
    "Prior",
    "SensitivityReport",
    "SobolIndices",
    "StrategicValue",
    "SweepPoint",
    "SweepResult",
    "VarianceDecomposition",
    "abc_rejection",
    "analyse_power",
    "apply_exclusions",
    "bootstrap_scales",
    "build_figures",
    "build_parameter_space",
    "build_preregistration",
    "combine_evidence",
    "compute_frontier",
    "confidence_sequence",
    "decompose",
    "decompose_all",
    "default_priors",
    "directional_evidence",
    "evidence_bars",
    "grouped_bars",
    "load_seal",
    "load_series",
    "network_diagram",
    "paired_dots",
    "plan_campaign",
    "posterior_predictive_check",
    "prior_widths",
    "required_replicates",
    "resolve_series",
    "sequential_abc",
    "series_from_aggregates",
    "sobol_analysis",
    "strategic_scatter",
    "strategic_value",
    "summary_distance",
    "synthetic_series",
    "verify_seal",
    "write_figures",
]
